GEN/urls.py
from django.urls import path
from GEN import views
# from .views import EnterPriseForm

app_name = 'GEN'

urlpatterns =[
path('',views.get_html_index, name = "index"),
path('safez/',views.get_html_safez, name = ""),
path('safez/privacy-policy/',views.get_html_privacy_policy, name = ""),
path('safez/terms-of-use/',views.get_html_terms_and_conditions, name = ""),
path('user_login/',views.user_login, name = "user_login"),

path('StoreBranchList/',views.StoreBranchList.as_view(), name = "StoreBranchList"),
path('StoreBranchListAdmin/',views.StoreBranchListAdmin.as_view(), name = "StoreBranchListAdmin"),
path('StoreCategoryListAd/',views.StoreCategoryListAd.as_view(), name = "StoreCategoryListAd"),
path('StoreUomList/',views.StoreUomList.as_view(), name = "StoreUomList"),
path('StoreCategoryList/',views.StoreCategoryList.as_view(), name = "StoreCategoryList"),
path('BranchAgentList/',views.BranchAgentList.as_view(), name = "BranchAgentList"),
path('index/',views.index, name = "index"),
path('orders_list/', views.orders_list, name = "orders_list"),
path('change_product_status/', views.change_product_status, name = "change_product_status"),
# path('EnterPriseForm/', views.EnterPriseForm.as_view(), name = "EnterPriseForm"),
path('orders_list/',views.orders_list, name = "orders_list1"),
path('order_create/',views.order_create, name = "order_create"),

path('GetBrandBranchDetailAdmin/',views.GetBrandBranchDetailAdmin.as_view(), name = "GetBrandBranchDetailAdmin"),
path('CreateBrandBranch/',views.CreateBrandBranch.as_view(), name = "CreateBrandBranch"),
path('CreateUpdateDataset/',views.CreateUpdateDataset.as_view(), name = "CreateUpdateDataset"),
path('CreateProductCategory/',views.CreateProductCategory.as_view(), name = "CreateProductCategory"),
path('CreateProduct/',views.CreateProduct.as_view(), name = "CreateProduct"),

path('login/',views.user_login, name = "login"),
path('logout/',views.user_logout, name = "logout"),
path('validate_user/',views.validate_user, name = "validate_user"),
path('authenticate_app_user/',views.authenticate_app_user, name = "authenticate_app_user"),
path('register_user/',views.register_user, name = "register_user"),
path('RegisterAgent/',views.RegisterAgent, name = "RegisterAgent"),
path('ProductList/', views.ProductList.as_view(), name = "ProductList"),
path('UpdateUserDetails/', views.UpdateUserDetails.as_view(), name = "UpdateUserDetails"),
path('UpdateServisableCategoryDetails/', views.UpdateServisableCategoryDetails.as_view(), name = "UpdateServisableCategoryDetails"),
path('UpdateServisableProduct/', views.UpdateServisableProduct.as_view(), name = "UpdateServisableProduct"),
path('UpdateCategoryDetails/', views.UpdateCategoryDetails.as_view(), name = "UpdateCategoryDetails"),
path('BranchProductListAdmin/', views.BranchProductListAdmin.as_view(), name = "BranchProductListAdmin"),
path('BrandProductListAdmin/', views.BrandProductListAdmin.as_view(), name = "BrandProductListAdmin"),
path('BranchProductListServisableCategorySpecific/', views.BranchProductListServisableCategorySpecific.as_view(), name = "BranchProductListServisableCategorySpecific"),
path('BranchProductListServisableCategorySpecificDisabled/', views.BranchProductListServisableCategorySpecificDisabled.as_view(), name = "BranchProductListServisableCategorySpecificDisabled"),
path('BranchProductListCustomer/', views.BranchProductListCustomer.as_view(), name = "BranchProductListCustomer"),
path('BranchProductListAdmin2/', views.BranchProductListAdmin2.as_view(), name = "BranchProductListAdmin2"),
path('BranchProductSupportDataCustomer/', views.BranchProductSupportDataCustomer.as_view(), name = "BranchProductSupportDataCustomer"),

path('SymptomSet/', views.SymptomSet.as_view(), name = "SymptomSet"),
path('CustomerOrder/', views.CustomerOrder.as_view(), name = "CustomerOrder"),
path('AgentDetail_AD/', views.AgentDetail_AD.as_view(), name = "AgentDetail_AD"),
path('CustomerOrderUpcoming/', views.CustomerOrderUpcoming.as_view(), name = "CustomerOrderUpcoming"),
path('CustomerOrderOthers/', views.CustomerOrderOthers.as_view(), name = "CustomerOrderOthers"),
path('OrderAcceptedByAgent/', views.OrderAcceptedByAgent.as_view(), name = "OrderAcceptedByAgent"),
path('OrderRejectedByAgent/', views.OrderRejectedByAgent.as_view(), name = "OrderRejectedByAgent"),
path('OrderCancelledByAgent/', views.OrderCancelledByAgent.as_view(), name = "OrderCancelledByAgent"),
path('OrderMarkedNoShowByAgent/', views.OrderMarkedNoShowByAgent.as_view(), name = "OrderMarkedNoShowByAgent"),
path('OrderMarkAsCompleted/', views.OrderMarkAsCompleted.as_view(), name = "OrderMarkAsCompleted"),
path('OrderMarkAsCheckedIn/', views.OrderMarkAsCheckedIn.as_view(), name = "OrderMarkAsCheckedIn"),

path('SamplePush/', views.SamplePush.as_view(), name = "SamplePush"),
path('BrandOrders/', views.BrandOrders.as_view(), name = "BrandOrders"),
path('BrandBranchOrders/', views.BrandBranchOrders.as_view(), name = "BrandBranchOrders"),
path('BrandBranchOrdersOngoing/', views.BrandBranchOrdersOngoing.as_view(), name = "BrandBranchOrdersOngoing"),
path('BrandBranchOrdersPendingApproval/', views.BrandBranchOrdersPendingApproval.as_view(), name = "BrandBranchOrdersPendingApproval"),
path('BrandBranchOrdersUpcoming/', views.BrandBranchOrdersUpcoming.as_view(), name = "BrandBranchOrdersUpcoming"),
path('GetOrderDetails01/', views.GetOrderDetails01.as_view(), name = "GetOrderDetails01"),
path('GetOrderAgentResponse/', views.GetOrderAgentResponse.as_view(), name = "GetOrderAgentResponse"),
path('BaGetOrderDetailswithActions/', views.BaGetOrderDetailswithActions.as_view(), name = "BaGetOrderDetailswithActions"),

path('product_list/', views.product_list, name = "product_list"),
path('change_order_status/', views.change_order_status, name = "change_order_status"),
path('alter_order_item/', views.alter_order_item, name = "alter_order_item"),
path('alter_order/', views.alter_order_item, name = "alter_order"),
path('order_details/', views.order_details, name = "order_details"),
path('order_list_user/', views.order_list_user, name = "order_list_user"),
path('order_create_m/', views.CreateOrder.as_view(), name = "order_create_m"),

path('customer_heatmap/', views.customer_heatmap, name = "customer_heatmap"),

path('validate_app/',views.validate_app, name = "validate_app"),
path('product_list_suggestion/',views.product_list_suggestion, name = "product_list_suggestion"),
path('get_user_suggestion_list/',views.get_user_suggestion_list, name = "get_user_suggestion_list"),
path('get_user_details/',views.get_user_details, name = "get_user_details"),
path('feed_contact/',views.feed_contact, name = "feed_contact"),
path('feed_news/',views.feed_news, name = "feed_news"),
path('submit_symptoms/',views.submit_symptoms, name = "submit_symptoms"),
path('customer_list/',views.customer_list, name = "customer_list"),
path('change_user_status/',views.change_user_status, name = "change_user_status"),


# path('posta/',views.posta, name = "posta"),
# posta
 ]

ierpa_base_flow_01/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('',include('GEN.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

GEN/views.py
import datetime
import json
import random
import string

from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from fcm_django.models import FCMDevice
from rest_framework.response import Response
from rest_framework.views import APIView

from DbUtils import db_operations_support, support_serializer_submit, support_db
from GEN import GEN_Constants
from GEN import dbconstants
from GEN import value_constant
from GEN.forms import UserFormCustomer, UserProfileInfoForm, IOrderForm, IOrderItemForm, OrderLogForm, OrderItemLogForm, \
    UserHealthProfileForm
from .models import Order, UserProfileInfo, OrderItem, \
    ProductCategory, Product, ProductBase, ItemMeasuementUnit, C19SymptomSet, BrandBranchBasicInfo, \
    BranchServisableCategory, BranchServisableProduct, \
    BranchServisableProductBase, AppUserType, BrandBasicInfo, OrderStatus, ServisableDaysCriteria
from .serialiserBase import EnterPriseForm, \
    CMN_CommunicationPhysicalModelSerializer, ProductCategorySerializer, ProductSerializer, ProductBaseSerializer, \
    ItemMeasuementUnitSerializer, C19SymptomSetSerializer, UserProfileInfoSerializer, UserProfileSuggestionSerializer, \
    ProductSuggestionListSerializer, \
    BrandBranchBasicInfoSerializer, BranchAgentListSerializer, BranchOrderListSerializer, OrderDetail01Serializer, \
    ProductCategorySerializerBranchUser, ServisableProductSerializerBranchUser, ServisableProductSerializerCustomer, \
    CustomerAllOrderSerializer, BranchDetailAdminSerializer, ProductCategorySerializerAd, StoreUomSerializer, \
    BrandBranchBasicInfoSerializerAD, BranchAgentDetailSerializer, BranchServisableProductSerializerAd, \
    ProductADFeedSerializer, BrandOrderListSerializer, OrderDetail01SerializerWithActions, OrderAgentResponseSerializer

import base64
from django.core.files.base import ContentFile

from .value_constant import get_display_translated_value



def get_api_language_preference(received_data):


    try:
        if "lang" in received_data:
            if received_data["lang"] == value_constant.KEY_LANGUAGE_TA:
                return value_constant.KEY_LANGUAGE_TA
            else:
                return value_constant.KEY_LANGUAGE_EN

        return value_constant.KEY_LANGUAGE_EN

    except:
        return value_constant.KEY_LANGUAGE_EN



def get_file_from_base64(b64_string):

    image_data = b64_string
    format, imgstr = image_data.split(';base64,')
    print("format", format)
    ext = format.split('/')[-1]

    data = ContentFile(base64.b64decode(imgstr))
    return data

    # file_name = "'myphoto." + ext
    # user.image.save(file_name, data, save=True)

class BrandBranchOrdersOngoing(APIView):

    def post(self,request):
        received_json_data=json.loads(request.body)
        api_lang = get_api_language_preference(received_json_data)
        print("reee")
        print(received_json_data)

        # phone = received_json_data["user_phone"]
        # user_p = UserProfileInfo.objects.get(phone_primary=phone)

        brandbranch_id = received_json_data["brand_branch_id"]
        brand_id = received_json_data["brand_id"]


        # order_list = Order.objects.filter(brand__id = brand_id, branch = brandbranch_id).order_by('-updated_at')

        order_list = Order.objects.filter(brand__id = brand_id, branch = brandbranch_id, order_status__code = GEN_Constants.ORDER_STATUS_ONGOING)

        order_list.filter()

        order_list = order_list.order_by('-updated_at')

        order_list_s = BranchOrderListSerializer(order_list, many=True)

        base_data = {}
        base_data["order"] = order_list_s.data
        base_data["delivery_text"] = "Order will bw delivered by 11 AM tomorrow"
        base_data["status_text"] = "RECEIVED"

        return Response(base_data)

class BrandBranchOrdersPendingApproval(APIView):

    def post(self,request):
        received_json_data=json.loads(request.body)
        api_lang = get_api_language_preference(received_json_data)
        print("reee")
        print(received_json_data)

        # phone = received_json_data["user_phone"]
        # user_p = UserProfileInfo.objects.get(phone_primary=phone)

        brandbranch_id = received_json_data["brand_branch_id"]
        brand_id = received_json_data["brand_id"]


        # order_list = Order.objects.filter(brand__id = brand_id, branch = brandbranch_id).order_by('-updated_at')

        order_list = Order.objects.filter(brand__id = brand_id, branch = brandbranch_id, order_status__code = GEN_Constants.ORDER_STATUS_INITIATED)
        # order_list = Order.objects.filter(brand__id = brand_id, branch = brandbranch_id)
        # order_list.filter()

        order_list = order_list.order_by('-updated_at')

        order_list_s = BranchOrderListSerializer(order_list, many=True)

        base_data = {}
        base_data["order"] = order_list_s.data
        base_data["delivery_text"] = "Order will bw delivered by 11 AM tomorrow"
        base_data["status_text"] = "RECEIVED"

        print("respisfssssssssssssss")
        print(base_data)

        return Response(base_data)

class BrandBranchOrdersUpcoming(APIView):

    def post(self,request):
        received_json_data=json.loads(request.body)
        api_lang = get_api_language_preference(received_json_data)

        print("reee")
        print(received_json_data)

        # phone = received_json_data["user_phone"]
        # user_p = UserProfileInfo.objects.get(phone_primary=phone)

        brandbranch_id = received_json_data["brand_branch_id"]
        brand_id = received_json_data["brand_id"]


        # order_list = Order.objects.filter(brand__id = brand_id, branch = brandbranch_id).order_by('-updated_at')

        order_list = Order.objects.filter(brand__id = brand_id, branch = brandbranch_id, order_status__code = GEN_Constants.ORDER_STATUS_AGENT_APPROVED)

        order_list.filter()

        order_list = order_list.order_by('schedule_requested_time')

        order_list_s = BranchOrderListSerializer(order_list, many=True)

        base_data = {}
        base_data["order"] = order_list_s.data
        base_data["delivery_text"] = "Order will bw delivered by 11 AM tomorrow"
        base_data["status_text"] = "RECEIVED"

        return Response(base_data)


def get_order_filter_type(filter_group):

    dataset = {}

    if filter_group == "ORD_GR_ONGOING":
        dataset["order_status__code"] = GEN_Constants.ORDER_STATUS_ONGOING
    elif filter_group == "ORD_GR_UPCOMING":
        dataset["order_status__code"] = GEN_Constants.ORDER_STATUS_AGENT_APPROVED
    elif filter_group == "ORD_GR_PENDING_APPROVAL":
        dataset["order_status__code"] = GEN_Constants.ORDER_STATUS_INITIATED
    elif filter_group == "ORD_GR_REJECTED_ALL":
        dataset["order_status__code"] = GEN_Constants.ORDER_STATUS_INITIATED
    elif filter_group == "GR_ALL":
        pass

    return dataset



class BrandOrders(APIView):

    def post(self, request):
        received_json_data=json.loads(request.body)
        api_lang = get_api_language_preference(received_json_data)
        print("reee")
        print(received_json_data)
        brand_id = received_json_data["brand_id"]
        order_list = Order.objects.filter(brand__id = brand_id)


        if "page_no" in received_json_data:
            page_no = received_json_data["page_no"]
        else:
            page_no = 1

        if "branch_id" in received_json_data:
            order_list = order_list.filter(branch__id = received_json_data["branch_id"])

        # print("order_status_code===1")
        if "order_status_code" in received_json_data:
            # print("order_status_code===2")
            order_status_code = received_json_data["order_status_code"]
            if order_status_code != "ORD_ALL":
                # print("order_status_code===3")
                # print(order_status_code)
                order_list = order_list.filter(order_status__code = order_status_code)
                # order_list = order_list.filter(order_status__code = "ORD_APPROVED")


        # print("final liste count")
        # print("==="+str(order_list.count()))

        if "filter_start_date" in received_json_data:
            filter_start_date = received_json_data["filter_start_date"]
            order_list = order_list.filter(schedule_requested_time__gte = filter_start_date+" 00:00:00")

        if "filter_end_date" in received_json_data:
            filter_end_date = received_json_data["filter_end_date"]
            order_list = order_list.filter(schedule_requested_time__lte = filter_end_date+" 23:59:59")

        # print("c2==="+str(order_list.count()))
        order_list = order_list.order_by('-updated_at')


        order_list = get_paginated_data(order_list, page_no, page_size=GEN_Constants.ORDERS_LIST_COUNT_BUSINESS)
        # print("c3==="+str(order_list.count()))
        order_list_s = BrandOrderListSerializer(order_list, many=True)

        # order_list_s


        base_data = {}
        base_data["order"] = order_list_s.data
        base_data["delivery_text"] = "Order will bw delivered by 11 AM tomorrow"
        base_data["status_text"] = "RECEIVED"

        return Response(base_data)

class BrandBranchOrders(APIView):

    def post(self,request):
        received_json_data=json.loads(request.body)
        api_lang = get_api_language_preference(received_json_data)
        print("reee")
        print(received_json_data)

        # phone = received_json_data["user_phone"]
        # user_p = UserProfileInfo.objects.get(phone_primary=phone)

templates/GEN/customers.html
{% extends "GEN/base.html" %}
{% block body_block %}

<input type="hidden" id="ul_user_status" value="{% url 'GEN:change_user_status' %}" />

<div class="col-12  pl_20 pr_20">
<!-- <div class="float-left col-md-12 no-padding"> -->
  <div class="col-12 col-md-4 float-left pl_0">
    <h1 class="header_title float-left mt_15 w-100">Users </h1>
    <span class="font_14 float-left grey_color">120 reported cases</span>
  </div>
  <div class="col-md-8 float-right pr_0 mb_15">
    <input type="email" class="form-control float-left col-md-8 mt_15" placeholder="Search here..">
  </div>









<div class="common_container  pt_0">
  <div class="table-responsive">
      <table class="table">
          <thead>
            <tr>
              <th>Name</th>
              <th>COVID19 Status</th>
              <th>Symptons</th>
              <th>Gender</th>
              <th>Mobile</th>
              <th>Whatsapp</th>
              <th>Address</th>
              <th>Pincode</th>
              <th>City</th>
<!-- AIzaSyCME_QQ7e3dFgkxewLrscix1UkccdVjjwo -->
            </tr>
          </thead>
          <tbody>
            {% for user in users %}
              <tr>

                <td onclick="getUserOrderDetails('{{user.user_meta.username }}')">{{ user.user_meta.fullname }}</td>
                <td>{{ user.user_meta.c_status }}</td>
                <td>{{ user.user_profile.symptom_total }} %</td>
                <td>{{ user.user_profile.gender }}</td>
                <td>{{ user.user_profile.phone_primary }}</td>
                <td>{{ user.user_profile.phone_secondary }}</td>
                <td>{{ user.user_profile.location_area }}, {{ user.user_profile.location_sublocality }} </td>
                <td>{{ user.user_profile.location_pincode }}</td>
                <td>{{ user.user_profile.location_city }}</td>


              </tr>
            {% endfor %}
          </tbody>
        </table>
  </div>
</div>

{% if users.has_other_pages %}
<div class="col-md-12 float-left pr_0">
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if users.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ users.previous_page_number }}">Previous</a></li>
      {% else %}
      <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
      {% endif %}
      {% for i in users.paginator.page_range %}
      {% if users.number == i %}
      <li class="page-item active"><a class="page-link" href="#"><span>{{ i }}</span></a> </li>
      {% else %}
      <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
      {% endfor %}
      {% if users.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ users.next_page_number }}">Next </a></li>
      {% else %}
      <!-- <li class="disabled"><span>&raquo;</span></li> -->
      <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
      {% endif %}
    </ul>
  </nav>
</div>
<!-- <li class="page-item active"><span>{{ i }} <span class="sr-only">(current)</span></span></li> -->
{% endif %}

</div>


<div class="modal fade" id="user_order_view_alrt" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog model_register_boy" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="da_view_title">View Customer Order</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

          {% csrf_token %}


          <div class="common_container pt_0" >

           <table class="table" id="mytab1">
             <thead>
               <tr>
                 <th>Order Id</th>
                 <th>Order Items</th>
                 <th>Craeted On</th>
                 <th>Updated On</th>
               </tr>
             </thead>
             <tbody id="item_table">

             </tbody>

          </table>



          </div>


        </div>

      <div>
      </div>

      </div><!--BODY END HERE-->
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary float-left" data-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
<!-- da view ends  -->

{% endblock %}

templates/GEN/index2.html
{% extends "GEN/base.html" %}
{% block body_block %}



  <div class="col-md-12 col-lg-12 float-left col-12 no-padding mt_20">
    <div class="col-md-2 col-half-offset float-left col-12 pl_0">
      <div class="common_container dasboard_box bg_1">
        <span class="icon_set icon-package doashbord_icon"></span>
        <span class="doashbord_big_text">{{order_count}}</span>
        <h1 class="primary_title w-100">TOTAL ORDER</h1>

      </div>
    </div>
    <div class="col-md-2 col-half-offset float-left col-12 pl_0">
      <div class="common_container dasboard_box bg_2">
        <span class="icon_set icon-delivery-truck doashbord_icon"></span>
        <span class="doashbord_big_text">{{order_delivered}}</span>
        <h1 class="primary_title w-100">ORDER DELIVERED</h1>

      </div>
    </div>
    <div class="col-md-2 col-half-offset float-left col-12 pl_0">
      <div class="common_container dasboard_box bg_3">
        <span class="icon_set icon-group doashbord_icon"></span>
        <span class="doashbord_big_text">{{customers_count}}</span>
        <h1 class="primary_title w-100">CUSTOMERS</h1>

      </div>
    </div>
    <div class="col-md-2  col-half-offset float-left col-12 pl_0">
      <div class="common_container dasboard_box bg_4">
        <span class="icon_set icon-avatar doashbord_icon"></span>
        <span class="doashbord_big_text">{{delivery_boy_count}}</span>
        <h1 class="primary_title w-100">DELIVERY BOY</h1>

      </div>
    </div>
    <div class="col-md-2  col-half-offset float-left col-12 pl_0">
      <div class="common_container dasboard_box bg_2">
        <span class="icon_set icon-group doashbord_icon"></span>
        <span class="doashbord_big_text">{{customer_care_count}}</span>
        <h1 class="primary_title w-100">CUSTOMER CARE</h1>

      </div>
    </div>
  </div>



<div class="col-md-6 col-12 col-lg-6 float-left pt_30 pl_0">

  <div class="common_container p_15">
    <h1 class="header_title w-100 mt_10">Delivery Boy</h1>
    <ul class="worker_list pt_15">


<!-- delivery_agents -->

{% for user in delivery_agents %}

<li>
  <div class="workers_box">
      {% if user.user_profile.profile_pic %}
    <img src="{{ user.user_profile.profile_pic.url }}" >
    {% else %}
    <img src="" >
    {% endif %}
    <div class="workers_caption">
      <span class="workers_name">{{ user.user_meta.username }}</span>
      <span class="workers_location">
        {{ user.user_profile.location_area }} ,
        {{ user.user_profile.location_sublocality }}
      </span>
  </div>
  </div>
</li> <!--========== END of LI Tags =========-->
{% endfor %}


    </ul>
  </div>
</div>

{% endblock %}

templates/GEN/login2.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>I Delivery Services | CRM</title>
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"> -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:500,700&display=swap" rel="stylesheet">
  <script src="../static/js/jquery-3.4.1.js"></script>
  <link rel="stylesheet" href="../static/css/main.css">


</head>
{% block body_block %}
<div class="login_contianer">
  <input type="hidden" id="login_success" value="{% url 'GEN:index' %}" />
  <div class="col-lg-2 col-md-2 float-left"></div>
  <div class="col-12 col-lg-8 col-md-8 float-left">
    <div class="login_box">
      <div class="col-md-7 float-left no-padding col-6">
        <div class="left_login">
            <ul class="pro_list">
              <li><img src="/static/images/basket.svg" alt=""><span class="pro_list_text">Home Need</span></li>
              <li><img src="/static/images/stationery.svg" alt=""><span class="pro_list_text">Stationery</span></li>
              <li><img src="/static/images/basket.svg" alt=""><span class="pro_list_text">Personal Product</span></li>
              <li><img src="/static/images/basket.svg" alt=""><span class="pro_list_text">Food</span></li>
              <li><img src="/static/images/basket.svg" alt=""><span class="pro_list_text">Medicine</span></li>
              <li><img src="/static/images/basket.svg" alt=""><span class="pro_list_text">Pet Product</span></li>
            </ul>

        </div>
      </div>
      <div class="col-md-5 float-left no-padding col-6">
        <div class="right_login">
            <img src="/static/images/logo.svg" alt="">
          <span class="font_14 second_color w-100 float-left mt_30">WELCOME BACK</span>
          <h1 class="header_title float-left mb_20 w-100">Login to your account</h1>
          <form id="login_form" action="{% url 'GEN:login' %}" method="POST">

            {% csrf_token %}

            <div class="form-group col-12 col-md-12 float-left no-padding">
              <label for="exampleInputEmail1">User Name</label>
              <input type="text" name="username" id="username" class="form-control" placeholder="Enter email">
            </div>
            <div class="form-group col-12 col-md-12 float-left no-padding">
              <label for="exampleInputEmail1">Password</label>
              <input type="password" name="password" id="password" class="form-control" placeholder="Password">
            </div>
            <h1 id="error_el" class="header_title float-left mb_20 w-100"> </h1>
            <a onclick="proceedUserLogin()" name="" value="Login" class="btn primary_btn mt_10">login</a>

          </form>
        </div>
      </div> <!--Left END-->
    </div>

    </div>
  <div class="col-lg-2 col-md-2 float-left"></div>
</div>
<script src="{% static "js/delivery_agents.js" %}" > </script>

{% endblock %}

templates/GEN/registration.html
{% extends "GEN/base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="jumbotron">


  {% if registered %}
  <h1>Registerion successful!</h1>
  {% else %}
  <h1>Delivery Agent Registation</h1>
  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{user_form.as_p}}
    {{profile_form.as_p}}

    <input type="submit" name="" value="Register">
  </form>
  {% endif %}

</div>

{% endblock %}